### PR TITLE
BSP:IO_Config:Remove useless i2c config and add touch key IO into gpi…

### PR DESCRIPTION
**Pull request by James19891004**
…o-key driver

## Proposed change(s)

Describe the changes made in this PR.

### Useful links (GitHub issues, forum threads, etc.)

Provide any relevant links here.

### Types of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code refactor (non-breaking change which refactor the code)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update only
- [ ] Other (please describe)

## Testing and Verification

Please describe the tests that you ran to verify your changes. Please also provide instructions and ROS packages as appropriate so we can reproduce the test environment.

1. 1st command
2. 2nd command
3. ...

## Test Configuration

__Mini Pupper Version__  
[e.g. Simulator, Mini Pupper, Mini Pupper 2, Mini Pupper 2 Pro]

__Raspberry Pi OS + ROS version__  
[e.g. Ubuntu 22.04, ROS 2 Humble]

__PC OS + ROS version__  
[e.g. Ubuntu 22.04, ROS 2 Humble]

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/mangdangroboticsclub/mini_pupper_2_bsp/blob/main/CONTRIBUTING.md) guidelines.
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

### CODE REVIEW

**Comment by James19891004** [comment]
Remove useless i2c  config and bring up touch key feature.

**Comment by hdumcke** [comment]
Overall it looks good to me, thanks for cleaning up the config.txt file

One issue I have is the number of touch buttons. If I understand correctly only 3 buttons are physically available
However there are 4 dtoverlay=gpio-key lines in config.txt

Can you update the GPIO chart in mini_pupper_2_issues and clarify the exact status of GPIO 16 please? Can we free this GPIO up?

**Comment by mangdangroboticsclub** [comment]
It's hard to set GPIO 16 to an extension for the user, so now add 4th touch button using GPIO 16, thanks

**Comment by hdumcke** [comment]
What is the status of this? Applying the config.txt file will change serial bus settings and break applications. Enabling uart2 will create /dev/ttyAMA1 and uart3 that is used for communicating with ESP32 will then use /dev/ttyAMA2

Can we merge this branch and I will then fix all the broken applications?

**Comment by hdumcke** [comment]
Looks like enabling uart2 has even more side effects. The behavior of UART used to communicate with ESP32 is changing as well.

Do not merge this PR until we have tested it thoroughly

**Comment by mangdangroboticsclub** [comment]
UART0 -> AMA0 (BT)
UART2-> AMA1 (Lidar?)
UART3 -> AMA2 (ESP32 proxy)

a new UART brings up a /dev/ttyAMA node. and the node number changed, which made ESP32 disconnect with CM4.
we'll change the uart device node in userspace
esp32_proxy/esp32-proxy.cpp
-static char const * filename {"/dev/ttyAMA1"};
+static char const * filename {"/dev/ttyAMA2"};

**Comment by mangdangroboticsclub** [comment]
Need add the below change point,
ubuntu@minipupperv2:~/ros2_ws/src/mini_pupper_ros$ git diff
diff --git a/mini_pupper_bringup/launch/lidar.launch.py b/mini_pupper_bringup/launch/lidar.launch.py
index 11a8b7a..2aaed6e 100644
--- a/mini_pupper_bringup/launch/lidar.launch.py
+++ b/mini_pupper_bringup/launch/lidar.launch.py
@@ -31,7 +31,7 @@ def generate_launch_description():
                 {'product_name': 'LDLiDAR_LD06'},
                 {'topic_name': 'scan'},
                 {'frame_id': 'lidar_link'},
               - {'port_name': '/dev/ttyUSB0'},
               + {'port_name': '/dev/ttyAMA1'},
                 {'port_baudrate': 230400},

**Pull request merged**
